### ISSUE TITLE
is there captcha feature ? 

### ISSUE THREAD

**Issue by kevincaradant** [steves/node-jira#132]
Hi

I'm looking for the captcha feature, but i don't see it.

Is it available or not yet ?

Thank you in advance :)

**Comment by mtscout6** [comment]
This repo is not actively maintained any more. Check out our [fork](https://github.com/jira-node/node-jira-client) and our release on [npm](https://www.npmjs.com/package/jira-client).

I don't see any Captcha support documented in Atlassian's [JIRA REST API Docs](https://docs.atlassian.com/jira/REST/latest/) unless I'm missing it and you can direct me to where Atlassian has documented that this feature is available on their end.

**Comment by kevincaradant** [comment]
ok thank you. Tape on google: captcha jira , you'll see some results  but the documentation is light about it: Maybe here: https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-version-2-tutorial but it's light too :/

**Comment by mtscout6** [comment]
> Be aware that you cannot use JIRA's REST API to authenticate with a JIRA site, once JIRA's CAPTCHA upon login feature has been triggered.

Directly from that doc you just linked. https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-version-2-tutorial#JIRARESTAPIVersion2Tutorial-CAPTCHAs

**Comment by quicksilver360** [comment]
You're getting the captcha most probably because you're making a lot of request that don't hit on target with JIRA, I have it happened to me and that was because I change my password every 3 months and I haven't changed my credentials used in the API. 
If you are getting this issue most probably you're not using it right. Try not to make many requests / second, and use the right password when accessing JIRA.

I don't see any way you could sent the captcha form through to another party tho.

Hope this helps.

**Comment by kevincaradant** [comment]
ok thank you guys  and yes it's because i try with one / two requests to know if credentials are right before to execute my others requests but sometimes i get a captcha on the real jira website but i don't see my 3 wrong requests or maybe it's a problem of requests by second ... In this case i will redirect a link to the JIRA on my application if i can't manage it directly with the API. thank you for the details and your help :)
